# Generated by Django 6.0.4 on 2026-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Емаил'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Полное Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('admin', 'администратор'), ('moderator', 'модератор')],
                default='moderator',
                max_length=20,
                verbose_name='Роль',
            ),
        ),
    ]
