# Generated by Django 6.0.4 on 2026-07-05 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID связанной сущности')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('card_created', 'Создание карточки'),
                            ('card_updated', 'Обновление карточки'),
                            ('moderation_request', 'Запрос на модерацию'),
                            ('moderation_approved', 'Одобрение модерации'),
                            ('moderation_rejected', 'Отказ в модерации'),
                        ],
                        max_length=32,
                        verbose_name='Тип уведомления',
                    ),
                ),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('data', models.JSONField(verbose_name='Дополнительные данные')),
                (
                    'recipient',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Получатель',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
