# Generated by Django 6.0.4 on 2026-08-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(
                choices=[
                    ('card_created', 'Создание карточки'),
                    ('card_updated', 'Обновление карточки'),
                    ('moderation_request', 'Запрос на модерацию'),
                    ('moderation_approved', 'Одобрение модерации'),
                    ('moderation_rejected', 'Отказ в модерации'),
                    ('instruction_source_updated', 'Обновление источника инструкции'),
                ],
                max_length=32,
                verbose_name='Тип уведомления',
            ),
        ),
    ]
