# Generated by Django 6.0.4 on 2026-07-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CategoryInfection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                (
                    'search_select_count',
                    models.PositiveIntegerField(default=0, verbose_name='Количество поисковых запросов'),
                ),
                ('search_weight', models.PositiveIntegerField(default=0, verbose_name='Поисковой вес')),
                (
                    'type',
                    models.CharField(
                        db_index=True,
                        error_messages={'null': 'Тип ингредиента нужно указать!'},
                        help_text='Тип ингредиента (обязательное поле).',
                        max_length=100,
                        verbose_name='Тип ингредиента',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Описание ингредиента (компонента вакцины)',
                        null=True,
                        verbose_name='Описание',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MethodsOfAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='Описание способа введения', null=True, verbose_name='Описание'
                    ),
                ),
                (
                    'list_icon_url',
                    models.ImageField(null=True, upload_to='admin-methods/list_icons/', verbose_name='Иконка в списке'),
                ),
                (
                    'detail_image_url',
                    models.ImageField(
                        null=True, upload_to='admin-methods/detail_images/', verbose_name='Детальная картинка'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Cпособ введения',
                'verbose_name_plural': 'Cпособы введения',
            },
        ),
        migrations.CreateModel(
            name='Infection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                (
                    'search_select_count',
                    models.PositiveIntegerField(default=0, verbose_name='Количество поисковых запросов'),
                ),
                ('search_weight', models.PositiveIntegerField(default=0, verbose_name='Поисковой вес')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reference_books.categoryinfection',
                        verbose_name='Категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Инфекция',
                'verbose_name_plural': 'Инфекции',
            },
        ),
    ]
