# Generated by Django 6.0.4 on 2026-05-26 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Infection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                (
                    'search_select_count',
                    models.PositiveIntegerField(default=0, verbose_name='Количество поисковых запросов'),
                ),
                ('search_weight', models.PositiveIntegerField(default=0, verbose_name='Поисковой вес')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='reference_books.category',
                        verbose_name='Категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Инфекция',
                'verbose_name_plural': 'Инфекции',
            },
        ),
    ]
