# Generated by Django 6.0.4 on 2026-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                (
                    'search_select_count',
                    models.PositiveIntegerField(default=0, verbose_name='Количество поисковых запросов'),
                ),
                ('search_weight', models.PositiveIntegerField(default=0, verbose_name='Поисковой вес')),
                (
                    'type',
                    models.CharField(
                        db_index=True,
                        error_messages={'null': 'Тип ингредиента нужно указать!'},
                        help_text='Тип ингредиента (обязательное поле).',
                        max_length=100,
                        verbose_name='Тип ингредиента',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Описание ингредиента (компонента вакцины)',
                        null=True,
                        verbose_name='Описание',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ('name',),
            },
        ),
    ]
