# Generated by Django 6.0.4 on 2026-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0002_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodsOfAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='Описание способа введения', null=True, verbose_name='Описание'
                    ),
                ),
                ('list_icon_url', models.URLField(verbose_name='Иконка в списке')),
                ('detail_image_url', models.URLField(verbose_name='Детальная картинка')),
            ],
            options={
                'verbose_name': 'Cпособ введения',
                'verbose_name_plural': 'Cпособы введения',
            },
        ),
    ]
