# Generated by Django 6.0.4 on 2026-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0003_methodsofadministration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodsofadministration',
            name='detail_image_url',
            field=models.ImageField(
                null=True, upload_to='admin-methods/detail_images/', verbose_name='Детальная картинка'
            ),
        ),
        migrations.AlterField(
            model_name='methodsofadministration',
            name='list_icon_url',
            field=models.ImageField(null=True, upload_to='admin-methods/list_icons/', verbose_name='Иконка в списке'),
        ),
    ]
