# Generated by Django 6.0.4 on 2026-07-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0004_alter_methodsofadministration_detail_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryinfection',
            options={'verbose_name': 'Категория инфекции', 'verbose_name_plural': 'Категории инфекций'},
        ),
        migrations.AddField(
            model_name='infection',
            name='old_id',
            field=models.IntegerField(blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='old_id',
            field=models.IntegerField(blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'),
        ),
        migrations.AddField(
            model_name='methodsofadministration',
            name='old_id',
            field=models.IntegerField(blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'),
        ),
    ]
