# Generated by Django 6.0.4 on 2026-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0004_alter_methodsofadministration_detail_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infection',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярность'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
