# Generated by Django 6.0.4 on 2026-07-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0005_infection_popularity_ingredients_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodsofadministration',
            name='code',
            field=models.SlugField(null=True, unique=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='methodsofadministration',
            name='note',
            field=models.TextField(
                blank=True, help_text='Описание способа введения', null=True, verbose_name='Описание 2'
            ),
        ),
    ]
