# Generated by Django 6.0.4 on 2026-07-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0005_alter_categoryinfection_options_infection_old_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='old_id',
        ),
    ]
