# Generated by Django 6.0.4 on 2026-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0006_methodsofadministration_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infection',
            name='old_id',
            field=models.IntegerField(
                blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'
            ),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='old_id',
            field=models.IntegerField(
                blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'
            ),
        ),
    ]
