# Generated by Django 6.0.4 on 2026-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0007_infection_old_id_ingredients_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodsofadministration',
            name='old_id',
            field=models.IntegerField(
                blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'
            ),
        ),
    ]
