# Generated by Django 6.0.4 on 2026-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0008_methodsofadministration_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodsofadministration',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='methodsofadministration',
            constraint=models.UniqueConstraint(fields=('name', 'detail_image_url'), name='unique_method_name_image'),
        ),
    ]
