# Generated by Django 6.0.4 on 2026-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0011_alter_methodsofadministration_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='methodsofadministration',
            name='unique_method_name_image',
        ),
        migrations.AddConstraint(
            model_name='methodsofadministration',
            constraint=models.UniqueConstraint(fields=('name', 'old_id'), name='unique_name_old_id'),
        ),
    ]
