# Generated by Django 6.0.4 on 2026-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0012_remove_methodsofadministration_unique_method_name_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodsofadministration',
            name='detail_image_url',
            field=models.ImageField(
                blank=True, null=True, upload_to='admin-methods/detail_images/', verbose_name='Детальная картинка'
            ),
        ),
        migrations.AlterField(
            model_name='methodsofadministration',
            name='list_icon_url',
            field=models.ImageField(
                blank=True, null=True, upload_to='admin-methods/list_icons/', verbose_name='Иконка в списке'
            ),
        ),
    ]
