# Generated by Django 6.0.4 on 2026-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0013_alter_methodsofadministration_detail_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodsofadministration',
            name='code',
            field=models.SlugField(
                choices=[
                    ('intramuscularly', 'Внутримышечно'),
                    ('subcutaneously', 'Подкожно'),
                    ('cutaneously', 'Кожно'),
                    ('intradermally', 'Внутрикожно'),
                    ('drops', 'Капли'),
                    ('pills', 'Таблетки'),
                    ('intranasally', 'Интраназально'),
                    ('inhalationally', 'Ингаляционно'),
                    ('instillation_bladder', 'Инстилляция в мочевой пузырь'),
                    ('other', 'Другое'),
                ],
                null=True,
                verbose_name='Код',
            ),
        ),
    ]
