STATUS_MAX_LEN = 50
MAX_DIGITS_SEARCH_WEIGHT = 10
DECIMAL_PLACES = 2
VERSION_STATUS_MAX_LEN = 50
NAME_MAX_LEN = 255
OFFICIAL_NAME_MAX_LEN = 500
IS_AVAILABLE_IN_RF_MAX_LEN = 255
MIN_AGE_MAX_LEN = 255
MAX_AGE_MAX_LEN = 255
PREGNANCY_USAGE_STATUS = 50
URL_MAX_LEN = 500
CONTRAINDICATION_TYPE_MAX_LEN = 20
INGREDIENT_ROLE_MAX_LEN = 20
AGE_GROUP_MAX_LEN = 100
COMMENT_MAX_LEN = 256
DEFAULT_VERSION = 1

# теги для schema
VACCINE_TAG = 'Вакцина'
