# Generated by Django 6.0.4 on 2026-07-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialinstruction',
            options={
                'ordering': ['title'],
                'verbose_name': 'Официальная инструкция',
                'verbose_name_plural': 'Официальные инструкции',
            },
        ),
        migrations.AlterField(
            model_name='officialinstruction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='officialinstruction',
            name='search_select_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество поисковых запросов'),
        ),
        migrations.AlterField(
            model_name='officialinstruction',
            name='search_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Поисковой вес'),
        ),
        migrations.AlterField(
            model_name='officialinstruction',
            name='source',
            field=models.CharField(default='ГРЛС', max_length=255, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='officialinstruction',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
