# Generated by Django 6.0.4 on 2026-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instructions', '0002_alter_officialinstruction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialinstruction',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Хэш текста инструкции'),
        ),
        migrations.AddField(
            model_name='officialinstruction',
            name='has_update',
            field=models.BooleanField(default=False, verbose_name='Обнаружено обновление'),
        ),
        migrations.AddField(
            model_name='officialinstruction',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней проверки источника'),
        ),
        migrations.AddField(
            model_name='officialinstruction',
            name='parsed_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст инструкции (из парсинга)'),
        ),
    ]
