# Generated by Django 6.0.4 on 2026-08-04 12:44

from django.db import migrations


def create_periodic_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='0', hour='3', day_of_week='1', day_of_month='*', month_of_year='*', timezone='UTC'
    )
    PeriodicTask.objects.get_or_create(
        task='instructions.tasks.check_official_instructions_updates',
        defaults={
            'name': 'Проверка обновлений источников инструкций (ГРЛС/ОХЛП)',
            'crontab': schedule,
            'enabled': True,
        },
    )


def delete_periodic_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(task='instructions.tasks.check_official_instructions_updates').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('instructions', '0003_officialinstruction_content_hash_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.RunPython(create_periodic_task, delete_periodic_task),
    ]
