# Generated by Django 6.0.4 on 2026-07-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contraindications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contraindication',
            options={
                'ordering': ['name'],
                'verbose_name': 'Противопоказание',
                'verbose_name_plural': 'Противопоказания',
            },
        ),
        migrations.AlterModelOptions(
            name='contraindicationcategory',
            options={
                'ordering': ['name'],
                'verbose_name': 'Категория противопоказания',
                'verbose_name_plural': 'Категории противопоказаний',
            },
        ),
        migrations.AddField(
            model_name='contraindication',
            name='old_id',
            field=models.IntegerField(
                blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'
            ),
        ),
        migrations.AlterField(
            model_name='contraindication',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                db_table='contraindication_categories_contraindications',
                related_name='contraindications',
                to='contraindications.contraindicationcategory',
                verbose_name='Категории',
            ),
        ),
        migrations.AlterField(
            model_name='contraindication',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название противопоказания'),
        ),
        migrations.AlterField(
            model_name='contraindication',
            name='search_select_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество поисковых запросов'),
        ),
        migrations.AlterField(
            model_name='contraindication',
            name='search_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Поисковой вес'),
        ),
        migrations.AlterField(
            model_name='contraindicationcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название категории'),
        ),
    ]
