# Generated by Django 6.0.4 on 2026-08-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contraindications', '0003_contraindication_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contraindication',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Популярность'),
        ),
    ]
