# Generated by Django 6.0.4 on 2026-06-26 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Тип сущности')),
                ('entity_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сущности')),
                (
                    'action_type',
                    models.CharField(
                        choices=[
                            ('login', 'Успешный вход'),
                            ('login_failed', 'Неудачная попытка входа'),
                            ('user_create', 'Создание нового редактора'),
                            ('role_change', 'Изменение роли пользователя'),
                            ('block', 'Блокировка/разблокировка учетной записи'),
                            ('card_create', 'Создание новой карточки'),
                            ('card_update', 'Сохранение изменений в черновик'),
                            ('card_submit', 'Отправка версии на модерацию'),
                            ('card_hide', 'Скрытие карточки'),
                            ('card_publish', 'Ручная публикация'),
                            ('card_delete', 'Архивация карточки'),
                            ('moderation_approve', 'Одобрение версии администратором'),
                            ('moderation_reject', 'Отклонение версии с комментарием'),
                        ],
                        max_length=100,
                        verbose_name='Тип действия',
                    ),
                ),
                ('details', models.TextField(blank=True, null=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        db_column='user_id',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Запись журнала аудита',
                'verbose_name_plural': 'Записи журнала аудита',
                'db_table': 'audit_logs',
                'ordering': ('-created_at',),
                'default_related_name': 'audit_logs',
            },
        ),
    ]
