# Generated by Django 6.0.4 on 2026-05-22 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Запись журнала аудита',
                'verbose_name_plural': 'Записи журнала аудита',
            },
        ),
    ]
