# Generated by Django 6.0.4 on 2026-07-04 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contraindications', '0001_initial'),
        ('reference_books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('active', 'Активна'),
                            ('archived', 'Архивирована'),
                            ('deleted', 'Удалена'),
                            ('draft', 'Черновик'),
                        ],
                        default='active',
                        max_length=50,
                        null=True,
                        verbose_name='Общий статус карточки',
                    ),
                ),
                ('is_visible', models.BooleanField(default=False, verbose_name='Видимость в поиске')),
                ('search_select_count', models.PositiveBigIntegerField(default=0, verbose_name='Счетчик запросов')),
                (
                    'search_weight',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name='Популярность (вес)'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_vaccine_cards',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Автор карточки',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='updated_vaccine_cards',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Редактор карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Карточка вакцины',
                'verbose_name_plural': 'Карточки вакцин',
                'db_table': 'vaccine_cards',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VaccineCardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='Порядковый номер версии')),
                (
                    'version_status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('draft', 'Черновик'),
                            ('pending_moderation', 'На модерации'),
                            ('approved', 'Одобрено'),
                            ('rejected', 'Отклонено'),
                            ('superseded', 'Заменена'),
                        ],
                        default='draft',
                        max_length=50,
                        null=True,
                        verbose_name='Статус версии',
                    ),
                ),
                (
                    'moderation_request',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='Ссылка на запрос модерации'),
                ),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вакцины')),
                (
                    'official_name',
                    models.CharField(blank=True, max_length=500, null=True, verbose_name='Официальное название'),
                ),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вакцины')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель')),
                (
                    'is_available_in_rf',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Доступность в РФ'),
                ),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный возраст')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный возраст')),
                (
                    'pregnancy_usage_status',
                    models.CharField(
                        blank=True,
                        choices=[('forbidden', 'Запрещено'), ('caution', 'С осторожностью'), ('safe', 'Без опасений')],
                        max_length=50,
                        null=True,
                        verbose_name='Применение при беременности',
                    ),
                ),
                ('storage_conditions', models.TextField(blank=True, null=True, verbose_name='Условия хранения')),
                (
                    'interaction_info',
                    models.TextField(blank=True, null=True, verbose_name='Информация о взаимодействии с препаратами'),
                ),
                (
                    'compatibility_info',
                    models.TextField(
                        blank=True, null=True, verbose_name='Информация о совместимости с другими вакцинами'
                    ),
                ),
                (
                    'schedule_info',
                    models.TextField(blank=True, null=True, verbose_name='Информация о схеме вакцинации'),
                ),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='Побочные эффекты')),
                ('indications', models.TextField(blank=True, null=True, verbose_name='Показания к применению')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('revision_date', models.DateField(blank=True, null=True, verbose_name='Дата ревизии')),
                (
                    'ohlp_url',
                    models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сайт ОХЛП'),
                ),
                (
                    'nonspec_url',
                    models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на вкладыш'),
                ),
                (
                    'instruction_url',
                    models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на инструкцию'),
                ),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на PDF')),
                (
                    'comment_source',
                    models.CharField(blank=True, max_length=256, null=True, verbose_name='Источник комментария АНО'),
                ),
                ('comment_ANO', models.TextField(blank=True, null=True, verbose_name='Комментарий АНО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создана версия')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Кем проверена версия')),
                (
                    'approved_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='approved_versions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Кем проверена версия',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_versions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Кем создана версия',
                    ),
                ),
                (
                    'parent_version',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Предыдущая версия',
                    ),
                ),
                (
                    'vaccine_card',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='vaccines.vaccinecard',
                        verbose_name='Ссылка на контейнер карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Версия вакцины',
                'verbose_name_plural': 'Версии вакцин',
                'db_table': 'vaccine_card_versions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='vaccinecard',
            name='current_version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_current',
                to='vaccines.vaccinecardversion',
                verbose_name='Текущая версия в работе',
            ),
        ),
        migrations.AddField(
            model_name='vaccinecard',
            name='published_version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_published',
                to='vaccines.vaccinecardversion',
                verbose_name='Опубликованная версия',
            ),
        ),
        migrations.CreateModel(
            name='VaccineCardVersionAdministrationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'age_group',
                    models.CharField(blank=True, max_length=100, null=True, verbose_name='Возрастная группа'),
                ),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                (
                    'administration_method',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_administration_methods',
                        to='reference_books.methodsofadministration',
                        verbose_name='Способ введения',
                    ),
                ),
                (
                    'vaccine_card_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Версия карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Связь версии со способом введения',
                'verbose_name_plural': 'Связи версий со способами введения',
                'db_table': 'vaccine_card_version_administration_methods',
            },
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='administration_methods',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionAdministrationMethod',
                to='reference_books.methodsofadministration',
            ),
        ),
        migrations.CreateModel(
            name='VaccineCardVersionContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'contraindication_type',
                    models.CharField(
                        choices=[('absolute', 'Абсолютное'), ('temporary', 'Временное')],
                        default='absolute',
                        max_length=20,
                        verbose_name='Тип противопоказания',
                    ),
                ),
                (
                    'contraindication',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_contraindications',
                        to='contraindications.contraindication',
                        verbose_name='Противопоказание',
                    ),
                ),
                (
                    'vaccine_card_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Версия карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Связь версии с противопоказанием',
                'verbose_name_plural': 'Связи версий с противопоказаниями',
                'db_table': 'vaccine_card_version_contraindications',
            },
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='contraindications',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionContraindication',
                to='contraindications.contraindication',
            ),
        ),
        migrations.CreateModel(
            name='VaccineCardVersionInfection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'infection',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_infections',
                        to='reference_books.infection',
                        verbose_name='Инфекция',
                    ),
                ),
                (
                    'vaccine_card_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Версия карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Связь версии с инфекцией',
                'verbose_name_plural': 'Связи версий с инфекциями',
                'db_table': 'vaccine_card_version_infections',
            },
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='infections',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionInfection',
                to='reference_books.infection',
            ),
        ),
        migrations.CreateModel(
            name='VaccineCardVersionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('active', 'Действующее'), ('excipient', 'Вспомогательное')],
                        default='excipient',
                        max_length=20,
                        verbose_name='Роль ингредиента',
                    ),
                ),
                (
                    'ingredient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_ingredients',
                        to='reference_books.ingredients',
                        verbose_name='Ингредиент',
                    ),
                ),
                (
                    'vaccine_card_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Версия карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Связь версии с ингредиентом',
                'verbose_name_plural': 'Связи версий с ингредиентами',
                'db_table': 'vaccine_card_version_ingredients',
            },
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionIngredient',
                to='reference_books.ingredients',
            ),
        ),
        migrations.AddConstraint(
            model_name='vaccinecardversionadministrationmethod',
            constraint=models.UniqueConstraint(
                fields=('vaccine_card_version', 'administration_method'), name='unique_version_administration_method'
            ),
        ),
        migrations.AddConstraint(
            model_name='vaccinecardversioncontraindication',
            constraint=models.UniqueConstraint(
                fields=('vaccine_card_version', 'contraindication'), name='unique_version_contraindication'
            ),
        ),
        migrations.AddConstraint(
            model_name='vaccinecardversioninfection',
            constraint=models.UniqueConstraint(
                fields=('vaccine_card_version', 'infection'), name='unique_vaccinecard_version_infection'
            ),
        ),
        migrations.AddConstraint(
            model_name='vaccinecardversioningredient',
            constraint=models.UniqueConstraint(
                fields=('vaccine_card_version', 'ingredient'), name='unique_version_ingredient'
            ),
        ),
        migrations.AddConstraint(
            model_name='vaccinecardversion',
            constraint=models.UniqueConstraint(fields=('vaccine_card', 'version_number'), name='unique_version'),
        ),
    ]
