# Generated by Django 6.0.4 on 2026-06-18 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('search_select_count', models.PositiveIntegerField(default=0)),
                ('search_weight', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_vaccine_cards',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='updated_vaccine_cards',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Карточка вакцины',
                'verbose_name_plural': 'Карточки вакцин',
                'db_table': 'vaccine_cards',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VaccineCardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('version_status', models.CharField(blank=True, max_length=128, null=True)),
                ('moderation_request', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('official_name', models.CharField(blank=True, max_length=128, null=True)),
                ('is_available_in_rf', models.BooleanField(default=False)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('pregnancy_usage_status', models.CharField(blank=True, max_length=128, null=True)),
                ('storage_conditions', models.TextField(blank=True, null=True)),
                ('interaction_info', models.TextField(blank=True, null=True)),
                ('compatibility_info', models.TextField(blank=True, null=True)),
                ('comment_ANO', models.TextField(blank=True, null=True)),
                ('ohlp_url', models.URLField(blank=True, null=True)),
                ('nonspec_url', models.URLField(blank=True, null=True)),
                ('instruction_url', models.URLField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                (
                    'approved_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='approved_versions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_versions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'parent_version',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='children',
                        to='vaccines.vaccinecardversion',
                    ),
                ),
                (
                    'vaccine_card',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vaccines.vaccinecard'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Версия вакцины',
                'verbose_name_plural': 'Версии вакцин',
                'db_table': 'vaccine_card_versions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='vaccinecard',
            name='current_version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_current',
                to='vaccines.vaccinecardversion',
            ),
        ),
        migrations.AddField(
            model_name='vaccinecard',
            name='published_version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_published',
                to='vaccines.vaccinecardversion',
            ),
        ),
        migrations.AddConstraint(
            model_name='vaccinecardversion',
            constraint=models.UniqueConstraint(fields=('vaccine_card', 'version_number'), name='unique_version'),
        ),
    ]
