# Generated by Django 6.0.4 on 2026-06-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_vaccine_cards',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор карточки',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='current_version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_current',
                to='vaccines.vaccinecardversion',
                verbose_name='Текущая версия в работе',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость в поиске'),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='published_version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_published',
                to='vaccines.vaccinecardversion',
                verbose_name='Опубликованная версия',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='search_select_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Счетчик запросов'),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='search_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Популярность (вес)'),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Общий статус карточки'),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='updated_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='updated_vaccine_cards',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Редактор карточки',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Кем проверена версия'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='approved_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='approved_versions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кем проверена версия',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='comment_ANO',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий АНО'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='compatibility_info',
            field=models.TextField(
                blank=True, null=True, verbose_name='Информация о совместимости с другими вакцинами'
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создана версия'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_versions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кем создана версия',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='instruction_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на инструкцию'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='interaction_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о взаимодействии с препаратами'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='is_available_in_rf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доступность в РФ'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='max_age',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='min_age',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='moderation_request',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ссылка на запрос модерации'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название вакцины'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='nonspec_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на вкладыш'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='official_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Официальное название'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='ohlp_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сайт ОХЛП'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='parent_version',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='vaccines.vaccinecardversion',
                verbose_name='Предыдущая версия',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на PDF'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='pregnancy_usage_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Применение при беременности'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='revision_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ревизии'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='storage_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия хранения'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='vaccine_card',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='versions',
                to='vaccines.vaccinecard',
                verbose_name='Ссылка на контейнер карточки',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='version_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер версии'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='version_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус версии'),
        ),
    ]
