# Generated by Django 6.0.4 on 2026-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0002_alter_vaccinecard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecard',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[('active', 'Активна'), ('archived', 'Архивирована'), ('deleted', 'Удалена')],
                default='active',
                max_length=50,
                null=True,
                verbose_name='Общий статус карточки',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='pregnancy_usage_status',
            field=models.CharField(
                blank=True,
                choices=[('forbidden', 'Запрещено'), ('caution', 'С осторожностью'), ('safe', 'Без опасений')],
                max_length=50,
                null=True,
                verbose_name='Применение при беременности',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='version_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('draft', 'Черновик'),
                    ('pending_moderation', 'На модерации'),
                    ('approved', 'Одобрено'),
                    ('rejected', 'Отклонено'),
                    ('superseded', 'Заменена'),
                ],
                default='draft',
                max_length=50,
                null=True,
                verbose_name='Статус версии',
            ),
        ),
    ]
