# Generated by Django 6.0.4 on 2026-06-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0003_methodsofadministration'),
        ('vaccines', '0004_vaccinecardversioncontraindication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversioncontraindication',
            name='vaccine_card_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)ss',
                to='vaccines.vaccinecardversion',
                verbose_name='Версия карточки',
            ),
        ),
        migrations.CreateModel(
            name='VaccineCardVersionAdministrationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'age_group',
                    models.CharField(blank=True, max_length=100, null=True, verbose_name='Возрастная группа'),
                ),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                (
                    'administration_method',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_administration_methods',
                        to='reference_books.methodsofadministration',
                        verbose_name='Способ введения',
                    ),
                ),
                (
                    'vaccine_card_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Версия карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Связь версии со способом введения',
                'verbose_name_plural': 'Связи версий со способами введения',
                'db_table': 'vaccine_card_version_administration_methods',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('vaccine_card_version', 'administration_method'),
                        name='unique_version_administration_method',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='VaccineCardVersionInfection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'infection',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_infections',
                        to='reference_books.infection',
                        verbose_name='Инфекция',
                    ),
                ),
                (
                    'vaccine_card_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Версия карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Связь версии с инфекцией',
                'verbose_name_plural': 'Связи версий с инфекциями',
                'db_table': 'vaccine_card_version_infections',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('vaccine_card_version', 'infection'), name='unique_vaccinecard_version_infection'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='VaccineCardVersionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('active', 'Действующее'), ('excipient', 'Вспомогательное')],
                        default='excipient',
                        max_length=20,
                        verbose_name='Роль ингредиента',
                    ),
                ),
                (
                    'ingredient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_ingredients',
                        to='reference_books.ingredients',
                        verbose_name='Ингредиент',
                    ),
                ),
                (
                    'vaccine_card_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)ss',
                        to='vaccines.vaccinecardversion',
                        verbose_name='Версия карточки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Связь версии с ингредиентом',
                'verbose_name_plural': 'Связи версий с ингредиентами',
                'db_table': 'vaccine_card_version_ingredients',
                'constraints': [
                    models.UniqueConstraint(
                        fields=('vaccine_card_version', 'ingredient'), name='unique_version_ingredient'
                    )
                ],
            },
        ),
    ]
