# Generated by Django 6.0.4 on 2026-06-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0005_alter_vaccinecardversioncontraindication_vaccine_card_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversion',
            name='comment_source',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Источник комментария АНО'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='version_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер версии'),
        ),
    ]
