# Generated by Django 6.0.4 on 2026-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contraindications', '0001_initial'),
        ('reference_books', '0003_methodsofadministration'),
        ('vaccines', '0006_vaccinecardversion_comment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversion',
            name='administration_methods',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionAdministrationMethod',
                to='reference_books.methodsofadministration',
            ),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='contraindications',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionContraindication',
                to='contraindications.contraindication',
            ),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вакцины'),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='indications',
            field=models.TextField(blank=True, null=True, verbose_name='Показания к применению'),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='infections',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionInfection',
                to='reference_books.infection',
            ),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='vaccine_versions',
                through='vaccines.VaccineCardVersionIngredient',
                to='reference_books.ingredients',
            ),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='schedule_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о схеме вакцинации'),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='side_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Побочные эффекты'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный возраст'),
        ),
    ]
