# Generated by Django 6.0.4 on 2026-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0007_vaccinecardversion_administration_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecard',
            name='status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('active', 'Активна'),
                    ('archived', 'Архивирована'),
                    ('deleted', 'Удалена'),
                    ('draft', 'Черновик'),
                ],
                default='active',
                max_length=50,
                null=True,
                verbose_name='Общий статус карточки',
            ),
        ),
    ]
