# Generated by Django 6.0.4 on 2026-07-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0008_alter_vaccinecard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecard',
            name='current_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_current',
                to='vaccines.vaccinecardversion',
                verbose_name='Текущая версия в работе',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecard',
            name='published_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards_as_published',
                to='vaccines.vaccinecardversion',
                verbose_name='Опубликованная версия',
            ),
        ),
    ]
