# Generated by Django 6.0.4 on 2026-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0009_alter_vaccinecard_current_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversioningredient',
            name='role',
            field=models.CharField(
                choices=[('active', 'Действующее'), ('auxiliary', 'Вспомогательное')],
                default='active',
                max_length=20,
                verbose_name='Роль ингредиента',
            ),
        ),
    ]
