# Generated by Django 6.0.4 on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


def bind_versions_to_official_instructions(apps, schema_editor):
    """Заполняет FK инструкции для версий с совпадающим URL."""
    official_instruction = apps.get_model('instructions', 'OfficialInstruction')
    vaccine_card_version = apps.get_model('vaccines', 'VaccineCardVersion')

    instruction_ids_by_url = dict(
        official_instruction.objects.values_list('url', 'id'),
    )
    versions = vaccine_card_version.objects.exclude(
        instruction_url__isnull=True,
    ).exclude(
        instruction_url='',
    )

    for version in versions.iterator():
        instruction_id = instruction_ids_by_url.get(version.instruction_url)
        if instruction_id:
            version.official_instruction_id = instruction_id
            version.save(update_fields=['official_instruction'])


def unbind_versions_from_official_instructions(apps, schema_editor):
    """Очищает FK инструкции при откате миграции."""
    vaccine_card_version = apps.get_model('vaccines', 'VaccineCardVersion')
    vaccine_card_version.objects.update(official_instruction=None)


class Migration(migrations.Migration):
    dependencies = [
        ('instructions', '0002_alter_officialinstruction_options_and_more'),
        ('vaccines', '0009_alter_vaccinecard_current_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversion',
            name='official_instruction',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vaccine_versions',
                to='instructions.officialinstruction',
                verbose_name='Официальная инструкция',
            ),
        ),
        migrations.RunPython(
            bind_versions_to_official_instructions,
            unbind_versions_from_official_instructions,
        ),
    ]
