# Generated by Django 6.0.4 on 2026-07-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contraindications', '0002_alter_contraindication_options_and_more'),
        ('reference_books', '0004_alter_methodsofadministration_detail_image_url_and_more'),
        ('vaccines', '0010_alter_vaccinecardversioningredient_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversioncontraindication',
            name='contraindication',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contraindications_relations',
                to='contraindications.contraindication',
                verbose_name='Противопоказание',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversioningredient',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ingredient_relations',
                to='reference_books.ingredients',
                verbose_name='Ингредиент',
            ),
        ),
    ]
