# Generated by Django 6.0.4 on 2026-07-13 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contraindications', '0002_alter_contraindication_options_and_more'),
        ('vaccines', '0011_alter_vaccinecardversioncontraindication_contraindication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversioncontraindication',
            name='contraindication',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='contraindications.contraindication',
                verbose_name='Противопоказание',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversioncontraindication',
            name='vaccine_card_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contraindications_relations',
                to='vaccines.vaccinecardversion',
                verbose_name='Версия карточки',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversioningredient',
            name='vaccine_card_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredient_relations',
                to='vaccines.vaccinecardversion',
                verbose_name='Версия карточки',
            ),
        ),
    ]
