# Generated by Django 6.0.4 on 2026-07-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0012_alter_vaccinecardversioncontraindication_contraindication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversionadministrationmethod',
            name='vaccine_card_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='administration_method_relations',
                to='vaccines.vaccinecardversion',
                verbose_name='Версия карточки',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversioninfection',
            name='vaccine_card_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='infection_relations',
                to='vaccines.vaccinecardversion',
                verbose_name='Версия карточки',
            ),
        ),
    ]
