# Generated by Django 6.0.4 on 2026-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0013_alter_vaccinecardversionadministrationmethod_vaccine_card_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversion',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на qr'),
        ),
    ]
