# Generated by Django 6.0.4 on 2026-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0014_vaccinecardversion_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecardversionadministrationmethod',
            name='age_group',
        ),
        migrations.AddField(
            model_name='vaccinecardversionadministrationmethod',
            name='age_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст от'),
        ),
        migrations.AddField(
            model_name='vaccinecardversionadministrationmethod',
            name='age_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст до'),
        ),
    ]
