# Generated by Django 6.0.4 on 2026-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0015_remove_vaccinecardversionadministrationmethod_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversionadministrationmethod',
            name='age_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Возрастная группа'),
        ),
    ]
