# Generated by Django 6.0.4 on 2026-07-14 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0010_vaccinecardversion_official_instruction'),
        ('vaccines', '0016_vaccinecardversionadministrationmethod_age_group'),
    ]

    operations = []
