# Generated by Django 6.0.4 on 2026-07-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0017_merge_20260714_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinecardversion',
            old_name='max_age',
            new_name='max_age_months',
        ),
        migrations.RenameField(
            model_name='vaccinecardversion',
            old_name='min_age',
            new_name='min_age_months',
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='is_available_in_rf',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доступность в РФ'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='pregnancy_usage_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Применение при беременности'),
        ),
    ]
