# Generated by Django 6.0.4 on 2026-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0018_rename_max_age_vaccinecardversion_max_age_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinecardversion',
            name='popularity',
        ),
        migrations.AddField(
            model_name='vaccinecard',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Популярность'),
        ),
    ]
