# Generated by Django 6.0.4 on 2026-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0019_remove_vaccinecardversion_popularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='is_available_in_rf',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступность в РФ'),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='pregnancy_usage_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Применение при беременности'),
        ),
    ]
