# Generated by Django 6.0.4 on 2026-07-15 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0020_alter_vaccinecardversion_is_available_in_rf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='parent_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='vaccines.vaccinecardversion',
                verbose_name='Предыдущая версия',
            ),
        ),
    ]
