# Generated by Django 6.0.4 on 2026-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0021_alter_vaccinecardversion_parent_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversion',
            name='age_allowed',
            field=models.CharField(default='', max_length=128),
        ),
    ]
