# Generated by Django 6.0.4 on 2026-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0022_vaccinecardversion_age_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='age_allowed',
            field=models.CharField(default='', max_length=128, verbose_name='Возраст применения'),
        ),
    ]
