# Generated by Django 6.0.4 on 2026-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0023_alter_vaccinecardversion_age_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecard',
            name='old_id',
            field=models.IntegerField(
                blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'
            ),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='code_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Английское название'),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='old_id',
            field=models.IntegerField(
                blank=True, help_text='ID из старой базы', null=True, unique=True, verbose_name='Старый ID'
            ),
        ),
        migrations.AddField(
            model_name='vaccinecardversion',
            name='pregnancy_usage_old',
            field=models.TextField(blank=True, null=True, verbose_name='Применение при беременности старое'),
        ),
    ]
