# Generated by Django 6.0.4 on 2026-07-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reference_books', '0009_alter_methodsofadministration_name_and_more'),
        ('vaccines', '0024_vaccinecard_old_id_vaccinecardversion_code_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vaccinecardversionadministrationmethod',
            name='unique_version_administration_method',
        ),
        migrations.AddConstraint(
            model_name='vaccinecardversionadministrationmethod',
            constraint=models.UniqueConstraint(
                fields=('vaccine_card_version', 'administration_method', 'age_from'),
                name='unique_version_administration_method',
            ),
        ),
    ]
