# Generated by Django 6.0.4 on 2026-07-24 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'vaccines',
            '0025_remove_vaccinecardversionadministrationmethod_unique_version_administration_method_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinecardversion',
            old_name='max_age_months',
            new_name='max_age_days',
        ),
        migrations.RenameField(
            model_name='vaccinecardversion',
            old_name='min_age_months',
            new_name='min_age_days',
        ),
    ]
