# Generated by Django 6.0.4 on 2026-08-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instructions', '0002_alter_officialinstruction_options_and_more'),
        ('vaccines', '0027_alter_vaccinecardversion_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='instruction_url',
            field=models.URLField(
                blank=True,
                help_text='Ссылка на инструкцию для специалистов, берется из ГРЛС',
                max_length=500,
                null=True,
                verbose_name='Ссылка на инструкцию',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='nonspec_url',
            field=models.URLField(
                blank=True,
                help_text='Ссылка для специалистов, с .pdf',
                max_length=500,
                null=True,
                verbose_name='Ссылка на вкладыш',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='official_instruction',
            field=models.ForeignKey(
                blank=True,
                help_text='Пока непонятно',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vaccine_versions',
                to='instructions.officialinstruction',
                verbose_name='Официальная инструкция',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='ohlp_url',
            field=models.URLField(
                blank=True,
                help_text='На данный момент не используется, но пусть будет',
                max_length=500,
                null=True,
                verbose_name='Ссылка на сайт ОХЛП',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='pdf_url',
            field=models.URLField(
                blank=True,
                help_text='Ссылка на ПДФ, хранящийся на сайте, создается администраторами',
                max_length=500,
                null=True,
                verbose_name='Ссылка на PDF',
            ),
        ),
        migrations.AlterField(
            model_name='vaccinecardversion',
            name='qr_code_url',
            field=models.URLField(
                blank=True,
                help_text='Ссылка на qr, пока непонятно',
                max_length=500,
                null=True,
                verbose_name='Ссылка на qr',
            ),
        ),
    ]
