# Generated by Django 6.0.4 on 2026-08-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0028_alter_vaccinecardversion_instruction_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversion',
            name='ingredients_text',
            field=models.TextField(
                blank=True, help_text='Состав вакцины полным текстом', null=True, verbose_name='Состав вакцины'
            ),
        ),
    ]
