# Generated by Django 6.0.4 on 2026-10-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vaccines', '0029_vaccinecardversion_ingredients_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecardversion',
            name='pregnancy_usage_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст применение при беременности'),
        ),
    ]
